homework2 ver. 1.0
neme3is/AleksandrIvanov pull request #2
Opened 2021-08-16 12:49 UTC by neme3is

2021-08-17 10:09 UTC, shoggy requested changes
Ex2 has same issues as the ex1, please fix them too

2021-08-17 10:09 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +                + "or contains(text(),'METALS & COLORS')]")).size(), 4);
Please choose more suitable locators. 
Remember order: DOM, CSS, XPath

2021-08-17 10:09 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +        webDriver.findElements(By.cssSelector("benefit-icon")).forEach(i -> softAssert.assertTrue(i.isDisplayed()));
Using loops inside for validation is a bad practice (in most cases). You can use AssertJ that has a matcher for collections (something like `assertThat(Collection).allMatch(...)`

2021-08-17 10:09 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +        ArrayList<String> texts = new ArrayList<>(Arrays
Please use interface for variable declaration and Java 9 has a static method `of(...)` that makes code better looking

2021-08-17 10:09 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +        list.forEach(i -> softAssert.assertTrue(i.isDisplayed()));
Please rewrite it using loop or streams and use matcher for collection

2021-08-17 10:09 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +                                       .size() > 0);
I think there is more suitable locator

2021-08-17 10:09 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +        softAssert.assertEquals(we.get(4).getAttribute("innerHTML").split("<br>"), texts1.get(4));
Please use another locator type
Use collections assertion

2021-08-17 14:10 UTC, neme3is commented on pom.xml
> +        </dependency>
No, we need test scope :)

2021-08-17 17:59 UTC, neme3is commented on src/test/java/com/epam/tc/hw2/Hw2TestsBaseClass.java
> +        webDriver.close();
Ok, i fixed this.

2021-08-23 20:43 UTC, shoggy requested changes

2021-08-23 20:43 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +    SoftAssertions softAssert = new SoftAssertions();
Move this variable declaration into Test-method

2021-08-23 20:43 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +            softAssert.assertThat(webDriver.findElement(By.linkText(i))
I think here we can use css selector that retrieves menu items, not by name

2021-08-23 20:43 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +            softAssert.assertThat(list.get(i).getText().replaceAll("\n", " "))
Make this conversion of the whole`list` before the assertion and compare two collections (expected and converted list)

2021-09-02 17:21 UTC, shoggy requested changes

2021-09-02 17:21 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +                  .isTrue();
Please use a specific method for collections size verification, something like `hasSize(...)`

2021-09-02 17:21 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/exercise2/ExerciseTwoTests.java
> +        }
Please do not use magic numbers (4 and 9 in this case)

2021-09-03 08:26 UTC, neme3is commented on src/test/java/com/epam/tc/hw2/exercise1/ExerciseOneTests.java
> +                  .isTrue();
fixed

2021-09-03 08:27 UTC, neme3is commented on src/test/java/com/epam/tc/hw2/exercise2/ExerciseTwoTests.java
> +        }
fixed

2021-09-10 14:51 UTC, shoggy approved these changes

2021-09-11 14:46 UTC, merged