homework3 ver. 1.0
neme3is/AleksandrIvanov pull request #3
Opened 2021-09-01 18:52 UTC by neme3is

2021-09-02 17:29 UTC, shoggy requested changes

2021-09-02 17:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw3/utils/TestUtils.java
> +            inputStream.close();
Do not do this manually, use try-with-resources instead

2021-09-02 17:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw3/Hw3TestsBaseClass.java
> +        "Colors: value changed to Green", "Colors: value changed to Red");
Please move these data to data provider and pass it to test methods as arguments

2021-09-02 17:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw3/exercise1/ExerciseOneTests.java
> +        softAssertions.assertThat(mainPageObject.getLoggedInUsername()).isEqualTo("ROMAN IOVLEV");
This string should be moved to the `.properties` file

2021-09-02 17:29 UTC, shoggy commented on src/test/java/com/epam/tc/hw3/exercise2/ExerciseTwoTests.java
> +        }
Convert `List<WebElement>` to `List<String>` and compare using one assertion, not in the loop

2021-09-03 19:24 UTC, neme3is commented on src/test/java/com/epam/tc/hw3/utils/TestUtils.java
> +            inputStream.close();
fixed

2021-09-04 08:54 UTC, neme3is commented on src/test/java/com/epam/tc/hw3/exercise1/ExerciseOneTests.java
> +        softAssertions.assertThat(mainPageObject.getLoggedInUsername()).isEqualTo("ROMAN IOVLEV");
done

2021-09-04 08:54 UTC, neme3is commented on src/test/java/com/epam/tc/hw3/Hw3TestsBaseClass.java
> +        "Colors: value changed to Green", "Colors: value changed to Red");
done

2021-09-04 08:54 UTC, neme3is commented on src/test/java/com/epam/tc/hw3/exercise2/ExerciseTwoTests.java
> +        }
done

2021-09-10 14:52 UTC, shoggy approved these changes

2021-09-11 15:24 UTC, merged