Homework4
neme3is/AleksandrIvanov pull request #5
Opened 2021-09-11 14:45 UTC by neme3is

2021-09-22 15:36 UTC, shoggy requested changes

2021-09-22 15:36 UTC, shoggy commented on pom.xml
> +                      </execution>
I think this is not required. Because it will be called only if test goal itself is successful

2021-09-22 15:36 UTC, shoggy commented on src/test/java/com/epam/tc/hw4/exercise2/ExerciseTwoTestSteps.java
> +        mainPageObject.login(TestUtils.getUsername(), TestUtils.getPass());
Pass user creds as method arguments here

2021-09-22 15:36 UTC, shoggy commented on src/test/java/com/epam/tc/hw4/failed/FailedTests.java
> +        softAssertions.assertThat(mainPageObject.getLoggedInUsername()).isEqualTo(TestUtils.getLoggedInUsername());
Please pass user creds and expected username as test-method arguments (from dataprovider)

2021-09-22 15:36 UTC, shoggy commented on .allure/allure-2.14.0/bin/allure
> +#!/usr/bin/env sh
Please remove `.allure` directory from git index

2021-09-26 09:56 UTC, neme3is commented on src/test/java/com/epam/tc/hw4/failed/FailedTests.java
> +        softAssertions.assertThat(mainPageObject.getLoggedInUsername()).isEqualTo(TestUtils.getLoggedInUsername());
fixed

2021-09-26 09:57 UTC, neme3is commented on .allure/allure-2.14.0/bin/allure
> +#!/usr/bin/env sh
fixed

2021-09-26 09:58 UTC, neme3is commented on pom.xml
> +                      </execution>
fixed

2021-09-26 09:58 UTC, neme3is commented on src/test/java/com/epam/tc/hw4/exercise2/ExerciseTwoTestSteps.java
> +        mainPageObject.login(TestUtils.getUsername(), TestUtils.getPass());
fixed

2021-09-27 17:59 UTC, shoggy approved these changes

2021-09-27 20:23 UTC, merged